name: Create ZIP

on:
  workflow_dispatch:
    # 允许手动触发工作流程

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # 检出main分支
        ref: main

    - name: Create ZIP
      run: |
        # 创建一个新目录用于存放ZIP文件
        mkdir -p zip-content
        # 复制目标文件夹到新目录
        cp -r image/二次元/avatar zip-content/
        # 创建ZIP文件
        zip -r avatar.zip zip-content/avatar
        # 列出文件以确认
        ls -lh

    - name: Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        # 上传ZIP文件
        name: avatar-zip
        path: avatar.zip