name: Create ZIP

on:
  push:
    branches:
      - main

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip and 7z
      run: |
        sudo apt-get update
        sudo apt-get install -y zip p7zip-full

    - name: Create a highly compressed zip file
      run: |
        # Create a standard zip file
        zip -r main.zip .

        # Use 7z to create a highly compressed zip file
        7z a -tzip -mx=9 main-compressed.zip main.zip

        # Remove the standard zip file as we no longer need it
        rm main.zip

    - name: Upload the highly compressed zip file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: main-compressed
        path: main-compressed.zip
